# Supported in docker 17.05
# ARG=version
# FROM bisque05$version-caffe:xenial
#FROM amilworks/bisque05-caffe-xenial:flour-v0.6.4
#FROM amilworks/bisque05-caffe-xenial:ENV-flour2
#FROM amilworks/bisque2:v1.0.0
FROM nail04.ece.ucsb.edu:5000/bisque3:v0.0.1


USER root

ENV BISQUE_UID 1000
ENV BISQUE_USER bisque


RUN  apt-get update \
     && apt-get install -y --allow-unauthenticated --no-install-recommends  \
        supervisor rsync nginx vim \
     && apt-get clean \
     && find  /var/lib/apt/lists/ -type f -delete \
     &&  wget -qqO /usr/bin/confd https://github.com/kelseyhightower/confd/releases/download/v0.11.0/confd-0.11.0-linux-amd64 \
    && chmod +x /usr/bin/confd


COPY etc/ /etc/
COPY virtrun /source/
COPY config/ /source/config/
COPY builder/  /builder/build-scripts.d/
COPY boot/ /builder/boot-scripts.d/
COPY start-bisque.sh /builder/start-scripts.d/R50-start-bisque.sh

# Copy the contents to the source (meancs bqcore goes to bqcore and modules goto modules
#ADD connoisseur /source/
#ADD builder/install-connoisseur.sh  /builder/
RUN /builder/run-bisque.sh build

#RUN rm -r modules

# OPENID 

# RUN mkdir -p /source/config/data/sstore/associations
# RUN mkdir -p /source/config/data/sstore/nonces
# RUN mkdir -p /source/config/data/sstore/temp

#USER $BISQUE_USER
#ENV  CONDOR_MANAGER_HOST master
CMD ["bootstrap", "start"]
